# Generated by Django 5.2.8 on 2026-06-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
