# Generated by Django 5.2.12 on 2026-06-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_customer_profile_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='MyShop', max_length=100)),
                ('store_tagline', models.CharField(blank=True, max_length=200)),
                ('store_description', models.TextField(blank=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('store_email', models.EmailField(blank=True, max_length=254)),
                ('store_phone', models.CharField(blank=True, max_length=20)),
                ('store_address', models.TextField(blank=True)),
                ('enable_razorpay', models.BooleanField(default=False)),
                ('razorpay_key', models.CharField(blank=True, max_length=100)),
                ('razorpay_secret', models.CharField(blank=True, max_length=100)),
                ('enable_cod', models.BooleanField(default=True)),
                ('enable_paypal', models.BooleanField(default=False)),
                ('paypal_client_id', models.CharField(blank=True, max_length=200)),
                ('paypal_secret', models.CharField(blank=True, max_length=200)),
                ('smtp_host', models.CharField(blank=True, max_length=100)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.EmailField(blank=True, max_length=254)),
                ('smtp_password', models.CharField(blank=True, max_length=100)),
                ('use_tls', models.BooleanField(default=True)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('force_ssl', models.BooleanField(default=False)),
                ('session_timeout', models.IntegerField(default=30)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('send_login_alerts', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
